AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 30

Resources:
  StudyNotionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: ./
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
      Environment:
        Variables:
          MONGODB_URI: "mongodb+srv://nishu55647:VRnJ75ibsaGgUZoh@cluster1.8oqemgd.mongodb.net/Study-Notion"
          JWT_SECRET: "babbar"
          CLOUDINARY_CLOUD_NAME: "duan4bxvh"
          CLOUDINARY_API_KEY: "396788268128351"
          CLOUDINARY_API_SECRET: "Z0NYWqqkb8UdKTaHkJqIMeYv1SQ"
          RAZORPAY_KEY_ID: "rzp_test_t4LUM04K0w6w4ic"
          RAZORPAY_SECRET: "D0dtPrJ2Rx0eJIdj1vAzmWYY"
          FRONTEND_URL: "https://d2iggsqshmb5f9.cloudfront.net"

Outputs:
  ApiUrl:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"